
### get resume
GET http://localhost:4003/resume
### create resume
POST http://localhost:4003/resume
Content-Type: application/json

{
    "id":1,
    "info":{
        "name":"(Yihu) Hubert Yu",
        "email":"hunt.yuyh@gmail.com",
        "tel":8076294237,
        "role":"Full Stack Developer"
    },
    "profile":[
        {
            "id":1,
            "myProfile":"2+ years work experience in software development, 6+ years programming experience.",
            "status":true
        },
        {
            "id":2,
            "myProfile":"Clean Coder, TDD, Restful API Builder, Full of Ambition, Creative, Curious for new technology, Eager to learn more.",
            "status":true
        },
        {
            "id":3,
            "myProfile":"Work Experience on Python Django REST Framework/PostgreSQL, React with Hooks/ExpressJS/Mongoose/GraphQL, Wordpress/MySQL.",
            "status":false
        },
        {
            "id":4,
            "myProfile":"Work Experience on  HTML/CSS/JavaScript, Redux, JQuery, PHP RESTFul API.",
            "status":true
        },
        {
            "id":5,
            "myProfile":"Knowledge on Server Architectures, Micro-services, Reverse Proxy, Replicas, Serverless.",
            "status":false
        },
        {
            "id":6,
            "myProfile":"Knowledge on AWS Instance, Nginx/Apache server,Load Balancer, DigitalOcean Server Set-up.",
            "status":false
        }
    ],
    "workExp":[
        {
            "id":1,
            "title":"Software Developer",
            "date":"Full time Aug 2020 - present",
            "address":"Fast Approach Inc -  3600 Steeles Ave E, Markham, ON L3R 9Z7",
            "description":[
                "Wordpress system setup, plugin install, ssh install digitalocean apache wordpress server setup, HTML/CSS/JavaScript develop." ,
                "Django system setup, with digitalocean nginx and gunicorn service.",
                "Wordpress Plugin design, used to upload, push and save data to real estate websites.",
                "Django framework on crawling and sending thousands of advertising emails to the clients, use MailGun API, crawling and parser yellow page information.",
                "E-commerce platform built up, using woocommerce wordpress plugin."
            ],
            "status":false
        },
        {
            "id":2,
            "title":" Web Developer",
            "date":"Full time Sept 2019 -Aug 2020",
            "address":"Singtao Media Group - 221 Whitehall Dr, Markham ON L3R 9T1, Canada",
            "description":[
                "Wordpress system setup, plugin install, ssh install digitalocean apache wordpress server setup, HTML/CSS/JavaScript develop." ,
                "Django system setup, with digitalocean nginx and gunicorn service.",
                "Wordpress Plugin design, used to upload, push and save data to real estate websites.",
                "Django framework on crawling and sending thousands of advertising emails to the clients, use MailGun API, crawling and parser yellow page information.",
                "E-commerce platform built up, using woocommerce wordpress plugin."
            ],
            "status":false
        }
    ],
    "compSkill":[
        {
            "id":1,
            "technology":"Angular",
            "level":9,
            "status":false
        },
        {
            "id":2,
            "technology":"Express",
            "level":9,
            "status":false
        },
        {
            "id":3,
            "technology":"Node",
            "level":9,
            "status":false
        },
        {
            "id":4,
            "technology":"Firebase",
            "level":9,
            "status":false
        }
    ],
    "eduExp":[
        {
            "id":1,
            "title":"Master of Engineering, Computer Engineering",
            "date":"2017 to 2019",
            "school":"Lakehead University",
            "description":[
                "Large scale data analysis missing values handling JupyterNotebook Python.",
                "Deep learning RCNN face recognition using Python tensorflow."
            ]
        },
        {
            "id":2,
            "title":" Bachelor of Engineering, Computer Engineering ",
            "date":"2013 to 2017",
            "school":"Nanchang University",
            "description":[
                "Digital signal processing system designed by Java.",
                "Basic knowledge of web development."
            ]
        }
    ]
}
###venpeople address
GET http://127.0.0.1:8000/yellow-page/api/venpeopel-address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbm8gcWkiLCJlbWFpbCI6ImZpbm8ucWlAZ21haWwuY29tIiwidXNlcklkIjoiZmlub3FpLUZFaUpWZkJYTk85ODZmZ0ZPUHROIiwiaWF0IjoxNTk3ODY0MDA2LCJleHAiOjE1OTc4ODU2MDZ9.nvAzkoYt0BRWw0AfdrV4K_R6ySymI1TOtGMF9f2VWgw

### create profile
POST http://localhost:5000/profiles/users-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbm8gcWkiLCJlbWFpbCI6ImZpbm8ucWlAZ21haWwuY29tIiwidXNlcklkIjoiZmlub3FpLUZFaUpWZkJYTk85ODZmZ0ZPUHROIiwiaWF0IjoxNTk3ODY0MDA2LCJleHAiOjE1OTc4ODU2MDZ9.nvAzkoYt0BRWw0AfdrV4K_R6ySymI1TOtGMF9f2VWgw

### upload profile image 
POST http://localhost:5000/profiles/users-profile/hubertyu-3LQj7dPm1wwSiFXok55r
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1YmVydCB5dSIsImVtYWlsIjoiaHVudC55dXloQGdtYWlsLmNvbSIsInVzZXJJZCI6Imh1YmVydHl1LTNMUWo3ZFBtMXd3U2lGWG9rNTVyIiwiaWF0IjoxNTk4MDk5OTI5LCJleHAiOjE1OTgxMjE1Mjl9.vREQk1-SJa0-45GAqzqcP1i7C_qorkuMmv1affY46Ps

### get the user profile
GET http://localhost:5000/profiles/users-profile/hubertyu-3LQj7dPm1wwSiFXok55r
Content-Type: application/json

### update the user profile 
PUT http://localhost:5000/profiles/users-profile/hubertyu-3LQj7dPm1wwSiFXok55r
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1YmVydCB5dSIsImVtYWlsIjoiaHVudC55dXloQGdtYWlsLmNvbSIsInVzZXJJZCI6Imh1YmVydHl1LTNMUWo3ZFBtMXd3U2lGWG9rNTVyIiwiaWF0IjoxNTk4MDk5OTI5LCJleHAiOjE1OTgxMjE1Mjl9.vREQk1-SJa0-45GAqzqcP1i7C_qorkuMmv1affY46Ps

{
    "info":[
            {
                "id":"8aAIQJxvdNe",
                "name":"profile1",
                "content":[
                    "aawd","qwdsad","sadfewfew","wesdf"
                ],
                "type":"inputList"
            }
        ]
}

### delete user profile
DELETE http://localhost:5000/profiles/users-profile/ZhuoranQi-pQR9bY4og8aAIQJxvdNe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlpodW9yYW4gUWkiLCJlbWFpbCI6ImNoZXJ5bGFubjAxMTBAaG90bWFpbC5jb20iLCJ1c2VySWQiOiJaaHVvcmFuUWktcFFSOWJZNG9nOGFBSVFKeHZkTmUiLCJpYXQiOjE1OTc2ODI0NTgsImV4cCI6MTU5NzcwNDA1OH0.Xdi2UkeH1P6NlPbvNkqEpKSmzDyUacrolkA5jM7Nq-s

### upload profile image 
PATCH http://localhost:5000/profiles/users-profile/hubertyu-3LQj7dPm1wwSiFXok55r
Content-Type: application/json

{
    "info":"hello world"
}

### reset password link
GET http://localhost:4000/password-management/hunt.yuyh@gmail.com
Content-Type: application/json

### reset password
PATCH http://localhost:4000/password-management/812HKYbJCczlooGfakY5
Content-Type: application/json

{
    "password":"123456"
}

### register user
POST http://localhost:4000/users-account
Content-Type: application/json

{
    "username":"yihu yu",
    "email":"qwe12311@gmail.com",
    "password":"123456"
}

### login user
POST http://localhost:4000/users-status
Content-Type: application/json

{
    "email":"fino.qi@gmail.com",
    "password":"123456"

}

### logout user
DELETE http://localhost:4000/users-status/fino.qi@gmail.com
Content-Type: application/json

### new access token
POST http://localhost:4000/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpbm8gcWkiLCJlbWFpbCI6ImZpbm8ucWlAZ21haWwuY29tIiwidXNlcklkIjoiZmlub3FpLUZFaUpWZkJYTk85ODZmZ0ZPUHROIiwiaWF0IjoxNTk3OTUxOTQyfQ.XCBFvmmsqKtF9K-6sp0yR7CvKiC_EbrEaM4uqysZR5A

### check email 
GET http://localhost:4000/users-account/hunt.yuyh@gmail.com
Content-Type: application/json

### graphql test
POST http://localhost:5001/graphql
Content-Type: application/json

{
    "query": "{ profile(page:1, limit:3) { previous{page limit} results{myProfile{name type content} userId{username email } image }  next{page limit } }}"
}
//{profile { previous { page limit} results { userId {email} } }}
//{ profile(page:1, limit:3) { previous{page limit} results{myProfile{name type content} userId{username email } image }  next{page limit } }}