### create profile
POST http://localhost:5000/profiles/users-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlpodW9yYW4gUWkiLCJlbWFpbCI6ImNoZXJ5bGFubjAxMTBAaG90bWFpbC5jb20iLCJ1c2VySWQiOiJaaHVvcmFuUWktcFFSOWJZNG9nOGFBSVFKeHZkTmUiLCJpYXQiOjE1OTc0MzY3ODEsImV4cCI6MTU5NzQ1ODM4MX0.JV6nQQwCCjqjIpnk7QApFGD3NemOdqTsdEDWCJ2xQ_E

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### get the user profile
GET http://localhost:5000/profiles/users-profile/Hubert-9rQE5FyuxgzAvmZsWgz5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1YmVydCIsImVtYWlsIjoieXl1MThAbGFrZWhlYWR1LmNhIiwiaWF0IjoxNTk3NDI5NTI4LCJleHAiOjE1OTc0NTExMjh9.B63p_Ezg3w4m8oEzYkFcuyisS2KQCqcvsg2j0MAjBLI


### reset password link
GET http://localhost:4000/password-management/hunt.yuyh@gmail.com
Content-Type: application/json

### reset password
PATCH http://localhost:4000/password-management/rchFlsuEhmXlWFfqbSrK
Content-Type: application/json

{
    "password":"123456"
}

### register user
POST http://localhost:4000/users-account
Content-Type: application/json

{
    "username":"Zhuoran Qi",
    "email":"cherylann0110@hotmail.com",
    "password":"123456"
}

### login user
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"cherylann0110@hotmail.com",
    "password":"123456"
}


